project:
    name: airflow-astro-project
    

pokemon_db:
  env:
    - AIRFLOW__CORE__SQL_ALCHEMY_CONN: postgresql+psycopg2://postgres:postgres@airflow-astro-project_e63762-postgres-1:5432/pokemon_db